on:
  push:
    branches:
      - release-please

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  # Create releases for merged release PRs.
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          target-branch: release-please
          skip-github-pull-request: true

      # Ensure that a tag is created, even if the release is created as a draft.
      # This works around https://github.com/googleapis/release-please-action/issues/962.
      # It also triggers the package action, which will mark it as not-a-draft when finished.
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
      - name: tag release
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git tag -d ${{ steps.release.outputs.tag_name }} || true
          git tag -a ${{ steps.release.outputs.tag_name }} -m "Release ${{ steps.release.outputs.tag_name }}"
          git push origin ${{ steps.release.outputs.tag_name }}

      # Add a comment with a durable link instead of the temporary unpublished one.
      - name: Comment on merged PR
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/github-script@v7
        with:
          script: |
            // The 'pr' output is a JSON string; parse it to get the PR number
            const prData = JSON.parse('${{ steps.release.outputs.pr }}');
            const prNumber = prData.number;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: 'ðŸ¤– Packaging action triggered; release here:\n\n\
              ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ steps.release.outputs.tag_name }}
              '
            });

      # Create PRs for new commits.
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          target-branch: release-please
          skip-github-release: true
