on:
  push:
    branches:
      - release-please

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  # Create releases for merged release PRs.
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          target-branch: release-please
          skip-github-pull-request: true

      # Ensure that a tag is created, even if the release is created as a draft.
      # This works around https://github.com/googleapis/release-please-action/issues/962.
      # It also triggers the package action, which will mark it as not-a-draft when finished.
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
      - name: tag release
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git tag -d ${{ steps.release.outputs.tag_name }} || true
          git tag -a ${{ steps.release.outputs.tag_name }} -m "Release ${{ steps.release.outputs.tag_name }}"
          git push origin ${{ steps.release.outputs.tag_name }}

      # Add a comment with a durable link instead of the temporary unpublished one.
      # Find the PR associated with this push, if there is one.
      # release-please doesn't give us PR info even though the docs say it will on release creation.
      - uses: jwalton/gh-find-current-pr@master
        id: pr
        if: steps.release.outputs.release_created
        with:
          state: closed
      - name: Comment on merged PR
        if: steps.release.outputs.release_created && steps.pr.outputs.number
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ steps.pr.outputs.number }};

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `ðŸ¤– Packaging action triggered; release here:

              ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ steps.release.outputs.tag_name }}`
            });

      # Create PRs for new commits.
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          target-branch: release-please
          skip-github-release: true
